<br /><br />
<div id="view-content">
<p>Echo: <?php echo $this->escape($this->sEcho); ?></p>
<p>Total Rows: <?php echo $this->escape($this->iTotalRecords); ?></p>
<p>Display Rows: <?php echo $this->escape($this->iTotalDisplayRecords); ?></p>
<table>
	<thead>
		<tr>
			<td>Trade Id</td>
			<td>Executed</td>
			<td>Start Date</td>
			<td>Maturity</td>
			<td>Term</td>
			<td>Currency</td>
			<td>Instrument</td>
			<td>Sub-type</td>
			<td>Price</td>
			<td>&nbsp;</td>
			<td>underlying 1</td>
			<td>underlying 2</td>
			<td>curr 1</td>
			<td>curr 2</td>
			<td>notional 1</td>
			<td>notional 2</td>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->aaData as $entry): ?>
		<tr>
			<td><?php echo $this->escape($entry['trade_id']); ?></td>
			<td><?php echo $this->escape($entry['execution_date']); ?></td>
			<td><?php echo $this->escape($entry['eff_date']); ?></td>
			<td><?php echo $this->escape($entry['end_date']); ?></td>
			<td><?php echo $this->escape($entry['term']); ?></td>
			<td><?php echo $this->escape($entry['currency']); ?></td>
			<td><?php echo $this->escape($entry['inst_type']); ?></td>
			<td><?php echo $this->escape($entry['inst_subtype']); ?></td>
			<td><?php echo $this->escape($entry['price']); ?></td>
			<td><?php echo $this->escape($entry['price_type']); ?></td>
			<td><?php echo $this->escape($entry['und_asset_1']); ?></td>
			<td><?php echo $this->escape($entry['und_asset_2']); ?></td>
			<td><?php echo $this->escape($entry['not_curr_1']); ?></td>
			<td><?php echo $this->escape($entry['not_curr_2']); ?></td>
			<td><?php echo $this->escape($entry['not_amount_1']); ?></td>
			<td><?php echo $this->escape($entry['not_amount_2']); ?></td>
		</tr>
		<?php endforeach; ?>
		</tbody>
		
	</table>
</div>