<br /><br />
<div id="view-content">
<p>Volume Data</p>
<table>
	<thead>
		<tr>
			<td>Date</td>
			<td>Daily Volume</td>
		</tr>
	</thead>
	<tbody>
		<?php $len = count($this->dates);
		for ($i = 0; $i < $len; $i++): ?>
		<tr>
			<td><?php echo $this->escape($this->dates[$i]); ?> </td>
			<td><?php echo $this->escape($this->volumes[$i]); ?>
		</tr>
		<?php endfor; ?>
		</tbody>		
	</table>
</div>