<br /><br />
<div id="view-content">
	<table>
		<thead>
			<tr>
				<td>ID</td>
				<td>Action</td>
				<td>Type</td>
				<td>Trade Id</td>
				<td>Executed</td>
				<td>Start Date</td>
				<td>Maturity</td>
				<td>Term</td>
				<td>Currency</td>
				<td>Instrument</td>
				<td>Sub-type</td>
				<td>Price</td>
			</tr>
		</thead>
		<tbody>
		<tr>
			<td><?php echo $this->escape($this->entry['id']); ?></td>
			<td><?php echo $this->escape($this->entry['action']); ?></td>
			<td><?php echo $this->escape($this->entry['type']); ?></td>
			<td><?php echo $this->escape($this->entry['data']['trade_id']); ?></td>
			<td><?php echo $this->escape($this->entry['data']['execution_date']); ?></td>
			<td><?php echo $this->escape($this->entry['data']['eff_date']); ?></td>
			<td><?php echo $this->escape($this->entry['data']['end_date']); ?></td>
			<td><?php echo $this->escape($this->entry['data']['term']); ?></td>
			<td><?php echo $this->escape($this->entry['data']['currency']); ?></td>
			<td><?php echo $this->escape($this->entry['data']['inst_type']); ?></td>
			<td><?php echo $this->escape($this->entry['data']['inst_subtype']); ?></td>
			<td><?php echo $this->escape($this->entry['data']['inst_subtype']); ?></td>
			<td><?php echo $this->escape($this->entry['data']['price']); ?></td>	
		</tr>
		</tbody>
		
	</table>
</div>