<!--  application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype(); ?>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Total Derivatives DTCC Rates Capture</title>
	<?php echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/global.css') ?>	
</head>
<body>
	<div id ="header" style="background-color: #EEEEEE; height : 30px;">
		<div id ="header-logo" style="float: left">
			<b>Rates Capture</b>
		</div>
	</div>
	<?php echo $this->layout()->content; ?>
</body>
</html>